# 예외
자바 개발자가 가장 신경 쓰기 귀찮아하는 것 중의 하나가 바로 예외처리다. 그래서 예외와 관련된 코드는 자주 엉망이 되거나 무성의하게 만들어지기 쉽다. 때론 잘못된 예외처리 코드 때문에 찾기 힘든 버그를 낳을 수도 있고, 생각지 않았던 예외상황이 발생했을 때 상상 이상으로 난처해질 수도 있다.

이번장에서는 JdbcTemplate을 대표로 하는 스프링의 데이터 액세스 기능에 담겨 있는 예외처리와 관련된 접근 방법에 대해 알아보자.

## 사라진 SQLException
3장에서 JdbcContext로 만들었던 코드를 스프링의 JdbcTempalte을 적용하도록 바꾸면서 얼렁뚱땅 넘어간 부분이 있다. 바꾸기 전후의 deleteAll() 메소드를 비교해보자.

~~~java
// 전
public void deleteAll() throws SQLException {
  this.jdbcContext.executeSql("delete from users");
}

// 후
public void deleteAll() {
  this.jdbcTemplate.update("delete from users");
}
~~~
바꾸기 전에 있던 throws SQLException 선언이 바꾼 뒤로는 사라졌다. SQLException 은 JDBC API 의 메소드들이 던지는 것이므로 당연히 있어야한다. 비록 로그를 남기기 위해 catch를 했다고 해도 다시 JDBC 템플릿 메소드밖으로 던져서 예외상황이 발생했다는 사실을 알려야 한다. 그런데 JdbcTemplate을 적용한 코드에서는 사라졌다. SQLException은 어디로 간 것일까?

### 초난감 예외처리
JdbcTemplate이 어떤 짓을 했길래 SQLException이 사라졌는지 알아보기 위해 먼저 개발자들의 코드에서 종종 발견되는 초난감 예외처리의 대표코드를 살펴보자.

#### 에외 블랙홀
~~~ java
// 초난감 예외처리 코드
try {
  ...
} catch(SQLException e) { }
~~~
여기서 catch(SQLException e) {} 는 예외 발생을 무시해버리고 정상적인 상황인 것처럼 다음 라인으로 넘어가겠다는 의도가 있는 게 아니라면 연습 중에도 절대 만들어서는 안 되는 코드다.

JDBC API를 썼더니 IDE가 빨간 줄을 그어주며 '처리되지 않은 예외가 있다'고 에러를 표시해 준다. 이를 보고 자바 기초로 배운 try/catch 블록을 둘러싸주는 것으로 해결한다. 물론 컴파일 에러 메세지도 없어지고 별 문제 없이 동작한다.

이런 식의 코드가 자바 서적의 예제나 강의 자료에도 심심치 않게 등장하고, 유명 오픈소스 제품의 코드나 실전 프로젝트의 작성된 코드에서도 나타나는 것을 보면 초보자의 실수라고만 볼 수는 없다. 이런 잘못된 습관이 계속 남아 있는 게 문제의 원인일 것이다.

예외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 정말 위험하다. 왜냐하면 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다.

결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동작하거나, 메모리나 리소스가 소진되거나, 예상치 못한 다른 문제를 일으킬 것이다. 최종적으로는 오작동을 하거나 시스템 오류가 나서 개발자가 알아차렸을 때는 이미 조치를 취하기에 늦다. 더 큰 문제는 그 시스템 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 매우 힘들다는 점이다.

어떤 경우에도 위와 같이 빈 catch 블록을 사용하면 안된다.

아래의 코드도 마찬가지다
~~~java
} catch(SQLException e) {
  System.out.println(e);
}
~~~

~~~java
} catch(SQLException e) {
  e.printStackTrace();
}
~~~

예외가 발생하면 화면에 출력해주는데 어떤 점이 문제일까? 다른 로그나 메세지에 금방 묻혀버리면 놓치기 쉽상이며, 운영서버에 올라가면 콘솔로그를 누군가가 계속 모니터링하지 않는 한 심각한 폭탄으로 남아 있을 것이다. **catch 블록을 이용해 화면에 메세지를 출력한 것은 예외 처리한 게 아니다.**

예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 한 가지다. **모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 개발자에게 분명하게 통보돼야 한다.**

SQLException이 발생하는 이유는 SQL에 문법 에러가 있거나 DB에서 처리할 수 없을 정도로 데이터 액세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다. 그런데 그냥 예외를 무시하고 정상적으로 동작하고 있는 것처럼 모른 척 다음 코드로 실행을 이어간다는 건 말이 되지 않는다. 콘솔이나 로그에 예외 메시지를 출력하는 건 아무런 도움이 되지 않는다.

차라리 아래와 같은 코드가 더 낫다
~~~java
//그나마 나은 예외처리
} catch(SQLException e) {
  e.printStackTrace();
  System.exit(1);
}
~~~

물론 실전에서 이렇게 만들라는 것은 아니다. 예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라는 의미다. 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다. 메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해버려라.

#### 무의미하고 무책임한 throws
catch 블록으로 예외를 잡아봐야 해결할 방법도 없고 JDK API나 라이브러리가 던지는 각종 이름도 긴 예외들을 처리하는 코드를 매번 throws로 선언하기도 귀찮아지기 시작하면, 아래와 같이 메소드 선언에 throws Exception을 기계적으로 붙이는 개발자도 있다.

~~~java
// 초난감 예외처리4
public void method1() throws Exception {
  method2();
  ...
}

public void method2() throws Exception {
  method3();
  ...
}

public void method3() throws Exception {
  ...
}
~~~

API 등에서 발생하는 예외를 일일이 catch하기 귀찮고, 별 필요도 없으며 매번 정확하게 예외 이름을 적어서 선언하기도 귀찮으니 아예 throws Exception이라는, 모든 예외를 무조건 던저버리는 선언을 모든 메소드에 기계적으로 넣는 것이다. 예외를 흔적도 없이 먹어치우는 예외 블랙홀보다는 조금 낫긴 하지만 이런 무책임한 throws 선언도 심각한 문제점이 있다.

자신이 사용하려고 하는 메소드에 throws Exception이 선언되어 있다고 생각해보자, 그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다. 결국 이런 메소드를 사용하는 메소드에서도 역시 throws Exception을 따라서 붙이는 수밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다를 수 있는 기회를 박탈당한다.

예외를 무시해버리는 첫 번째 문제보다는 낫다고 하지만 이런 코드도 매우 안좋은 예외처리 방법이다.

이 두 가지 나쁜 습관은 어떤 경우에도 용납하지 않아야 한다.

### 예외의 종류와 특징
그렇다면 예외를 어떻게 다뤄야 할까? 예외처리에 관해서는 자바 개발자들 사이에서도 오랫동안 많은 논쟁이 있었다. 가장 큰 이슈는 체크 예외(checked exception)라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다.

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.

- Error
첫번째는 java.lang.Error 클래스의 서브클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다. OutOfMemoryError나 ThreadDeath 같은 에러는 CATCH 블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다.
따라서 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다.

- Exception과 체크 예외
java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.
Exception 클래스는 다시 체크 예외와 언체크 예외(unchecked exception)로 구분된다. 전자는 Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것들이고, 후자는 RunTimeException을 상속한 클래스들을 말한다.
RunTimeException은  Exception의 서브클래스이므로 Exception의 일종이긴 하지만 자바는 이 RuntimeException과 그 서브클래스는 특별하게 다룬다. 아래는 Exception 클래스의 서브클래스를 체크 예외와 언체크 예외로 구분한 것이다.
~~~

~~~
일적으로 예외는 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다. 체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다. 사용할 메소드가 체크 예외를 던진다면 이를 catch 문으로 잡든지, 아니면 다시 throws를 정의해서 메소드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다.

- RuntimeException과 언체크/런타임 예외
java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 럼타임 예외라고도 한다. 에러와 마찬가지로 이 런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 된다. 물론 명시적으로 잡거나 선언해도 상관은 없다.
런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다. 대표적으로 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을 때 발생하는 NullPointerException이나, 허용되지 않는 값을 사용해서 메소드를 호출할 때 발생하는 IllegalArgumentException 등이 있다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다.

피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 마든 것이 런타임 예외다. 따라서 런타임 예외는 예상하지 못했던 예외상황에서 발생하는 게 아니기 때문에 굳이 catch나 throws를 사용하지 않아도 되도록 만든 것이다.

그런데 자바 언어를 설계하고 JDK를 개발한 사람들의 이런 설계의도는 현실과 잘 맞지 않았고 비난의 대상이 되기도 했다. 특히 체크 예외의 불필요성을 주장하는 사람들이 늘어갔다. 체크 예외가 예외처리를 강제하는 것 때문에 예외 블랙홀이나 무책임한 throws 같은 코드가 남발됐다. 최근에 새로 등장하는 자바 표준 스펙의 API들은 예상 가능한 예외상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있기도 하다.

### 예외처리 방법
일반적인 예외처리 방법을 살펴보고나서 효과적인 예외처리 전략을 생각해보자.

#### 예외 복구
첫 번째 처리 방법은 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다.

예를 들어 사용자가 요청한 파일을 읽으려고 시도했는데 어떤 문제로 읽히지 않아 IOException이 발생했다고 생각해보자. 이때는 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내해서 예외상황을 해결할 수 있다. 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해주는 것이다.

이런 경우 예외상황은 다시 정상으로 돌아오고 예외를 복구했다고 볼 수 있다. 단, IOException 에러 메세지가 사용자에게 그냥 던져지는 것은 예외 복구라고 볼 수 없다. 예외가 처리됐으면 비록 기능적으로는 사용자에게 예외상황으로 비쳐도 애플리케이션에서는 정상적으로 설계된 흐름을 따라 진행돼야 한다.

네트워크가 불안해서 가끔 서버에 접속이 잘 안 되는 열악한 환경에 있는 시스템이라면 원격 DB 서버에 접속하다 실패해서 SQLException이 발생하는 경우에 재시도를 해볼 수 있다. 네트워크 접속이 원할하지 않아서 예외가 발생했다면 일정 시간 대기했다가 다시 접속을 시도해보는 방법을 사용해서 예외상황으로부터 복구를 시도할 수 있다. 물론 정해진 횟수만큼 재시도해서 실패했다면 예외 복구는 포기해야 한다.

예외처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다. API를 사용하는 개발자로 하여금 예외상황이 발생할 수 있음을 인식하도록 도와주고 이에 대한 적절한 처리를 시도해보도록 요구하는 것이다.

아래는 통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY만큼 재시도를 하는 간단한 예이다. 사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구되게 할 수 있다.

~~~java
// 재시도를 통해 예외를 복구하는 코드
int maxretry = MAX_RETRY;
while(maxretry-- > 0) {
  try {
    ... // 예외가 발생할 가능성이 있는 시도
    return; // 작업 성공
  }
  catch(SomeException e) {
    // 로그 출력, 정해진 시간만큼 대기
  }
  finally {
    // 리소스 반납. 정리 작업
  }
}

throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
~~~

#### 예외처리 회피
두 번째 방법은 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다. throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 rethrow하는 것이다.

예외를 자신이 처리하지 않고 회피하는 방법이다. 빈 catch 블록으로 잡아서 예외가 발생하지 않은 것처럼 만드는 경우는, 드물지만 특별한 의도를 가지고 예외를 복구했거나 아무 개념이 없어서 그런 것이지 회피한 것은 아니다. 예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리할 수 있도록 아래처럼 던져줘야 한다.

~~~java
// 예외처리 회피1
public void sadd() throws SQLException {
  ///JDBC API
}
~~~

~~~java
// 예외처리 회피2
public void add() throws SQLException {
  try {
    // JDBC API
  }
  catch(SQLException e) {
    // 로그 출력
    throw e;
  }
}
~~~
JdbcContext나 JdbcTemplate이 사용하는 콜백 오브젝트는 메소드 선언을 보면 알겠지만 ResultSet이나 PreparedStatement등을 이용해서 작업하다 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. 콜백 오브젝트의 메소드는 모두 throws SQLException이 붙어 있다. SQLException을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문이다. 콜백 오브젝트의 메소드는 SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다.

하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다. 만약 DAO가 SQLException을 생각 없이 던져버리면 어떻게 될까? DAO를 사용하는 서비스 계층이나 웹 컨트롤러에서 과연 SQLException을 제대로 처리할 수 있을까? 아마도 이런 경우라면 DAO에서 던진 SLQLException을 서비스 계층 메소드가 다시 던지고, 컨트롤러도 다시 던지도록 선언해서 예외는 그냥 서버로 전달되고 말 것이다. 아마도 throws SQLException과 같이 구체적인 예외를 던지도록 선언하기가 귀찮아서 모든 예외를 생각없이 던져버리게 하는 throws Exception을 사용할 가능성이 높다.

예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야한다.

#### 예외 전환
마지막으로 예외를 처리하는 방법은 예외 전환(exception translation)을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것이다. 하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.

예외 전환은 보통 두 가지 목적으로 사용한다.
첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 핼줄 수 있는 예외로 바꿔주기 위해서다. API가 발생하는 기술적인 로우레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것이다.

예를 들어 새로운 사용자를 등록하려고 시도했을 때 아이디가 같은 사용자가 있어서 DB 에러가 발생하면 JDBC API는 SQLException을 발생시킨다. 이 경우 DAO 메소드가 SQLException을 그대로 밖으로 던져버리면, DAO를 이용해 사용자를 추가하려고 한 서비스 계층 등에서는 왜 SQLException이 발생헀는지 쉽게 알 방법이 없다. 로그인 아이디 중복 같은 경우는 충분히 예상 가능하고 복구 간으한 예외상황이다. 이럴 땐 DAO에서 SQLException의 정보를 해석해서 DuplicationUserIdException 같은 예외로 바꿔서 던져주는 게 좋다.

의미가 분명한 예외가 던져지면 서비스 계층 오브젝트에는 적절한 복구 작업을 시도할 수가 있다. 서비스 계층 오브젝트에서 SQLException의 원인을 해석해서 대응하는 것도 불가능하지는 않지만, 특정 기술의 정보를 해석하는 코드를 비즈니스 로직을 담은 서비스 계층에 두는 건 매우 어색하다. 따라서 DAO 메소드에서 기술에 독립적이며 의미가 분명한 예외로 전환해서 던져줄 필요가 있다.

아래는 사용자 정보를 등록하려고 시도해보고, 만약 중복된 아이디 값 때문에 에러가 나는 경우에는 이를 확인해서 좀 더 의미 있는 DuplicateKeyException으로 전환해주는 DAO메소드의 예다.

~~~java
// 예외 전환 기능을 가진 DAO 메소드
public void add(User user) throws DuplicateUserIdException, SQLException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
  }
  catch(SQLException e) {
    //ErrorCode가 MySQL의 Duplicate Entry(1062)이면 예외 전환
    if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw DuplicateUserIdException();
    else
      throw e;
  }
}
~~~
보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외(nested exception)로 만드는 것이 좋다. 중첩 예외는 getCause() 메소드를 이용해서 청므 발생한 예외가 무엇인지 확인할 수 있다. 중첩 예외는 아래처럼 새로운 예외를 만들면서 생성자난 initCause() 메소드로 근본 원인이 되는 예외를 넣어주면 된다.

~~~java
// 중첩 예외1
catch(SQLException e) {
  ...
  throw DuplicateUserIdException(e);
}
~~~
~~~java
// 중첩 예외2
catch(SQLException e) {
  ...
  throw DuplicateUserIdException().initCause(e);
}
~~~
두 번째 전환 방법은 예외를 처리하고 쉽고 단순하게 만들기 위해 포장(wrap)하는 것이다. 중첩 예외를 이용해 새로운 예외를 만들고 원인이 되는 예외를 내부에 담아서 던지는 방식은 같다. 하지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니다. 주로 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다.

대표적으로 EJBException을 들 수 있다. EJB 컴포넌트 코드에서 발생하는 대부분의 체크 예외는 비즈니스 로직으로 볼 때 의미 있는 예외이거나 복구 가능한 예외가 아니다. 이런 경우에는 런타임 예외인 EJBException으로 포장해서 던지는 편이 낫다. 아래 예처럼 말이다.

~~~java
// 예외 포장
try {
  OrderName orderName = EJBHomeFactory.getInstance().getOrderHome();
  Order order = orderHome.findByPrimaryKey(Integer id);
} catch(NamingException ne) {
  throw new EJBException(ne);
} catch(SQLException se) {
  throw new EJBException(se);
} catch(RemoteException re) {
  throw new EJBException(re);
}
~~~
EJBException은 RuntimeException 클래스를 상속한 런타임 예외다. 이렇게 런타임 예외로 만들어서 전달하면 EJB는 이를 시스템 익셉션으로 인식하고 트랜잭션을 자동으로 롤백해준다. 런타임 예외이기 때문에 EJB 컴포넌트를 사용하는 다른 EJB난 클라이언트에서 일일이 예외를 잡거나 다시 던지는 수고를 할 필요가 없다. 이런 예외는 잡아도 복구할 만한 방법이 없기 때문이다.

반대로 애플리케이션 로직상에서 예외조건이 발견되거나 예외상황이 발생할 수도 있다. 이런 것은 API가 던지는 예외가 아니라 애프리케이션 코드에서 의도적으로 던지는 예외다. 이때는 체크 예외를 사용하는 것이 적절하다. 비즈니스적인 의미가 있는 예외는 이에 대한 적절한 대응이나 복구 작업이 필요하기 때문이다.

**일반적으로 체크 예외를 계속 throws를 사용해 넘기는 건 무의미하다.** 메소드 선언은 지저분해지고 아무런 장점이 없다. DAO에서 발생한 SQLException이 웹 컨트롤러 메소드까지 명시적으로 전달된다고 해서 무슨 소용이 있을까? 웹 컨트롤러 메소드에 throws SQLException 선언이 달려 있다면 이를 도대체 어떻게 해석해야 할까? 어차피 복구가 불가능한 예외라면 가능한 한 빨리 런타임 예외로 포장해 던지게 해서 다른 계층의 메소드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 해줘야 한다.

대부분 서버환경에서는 애플리케이션 코드에서 처리하지 않고 전달된 예외들을 일괄적으로 다룰 수 있는 기능을 제공한다. 어차피 복구하지 못할 예외라면 애플리케이션 코드에서는 런타임 예외로 포장해서 던져버리고, 예외처리 서비스 등을 이용해 자세한 로그를 남기고, 관리자에게는 메일 등을로 통보해주고, 사용자에게는 친절한 안내 메시지를 보여주는 식으로 처리하는 게 바람직하다.

### 예외처리 전략
사실 자바의 예외를 이용하는 것은 간단하다. 하지만 예외를 효과적으로 사용하고, 예외가 발생하는 코드를 깔끔하게 정리하는 데는 여러 겨자 신경 써야 할 사항이 많다. 지금까지 살펴본 예외의 종류와 처리 방법 등을 기준으로 일관된 예외처리 전략을 정리해보자.

#### 런타임 예외의 보편화
일반적으로는 체크 예외가 일반적인 예외를 다루고, 언체크 예외는 시스템 장애나 프로그램상의 오류에 사용한다고 헀다. 문제는 체크 예외는 복구할 가능성이 조금이라도 있는, 말 그대로 예외적인 상황이기 때문에 자바는 이를 처리하는 catch 블록이나 throws 선언을 강제하고 있다는 점이다. 이렇게 예외처리를 강제하는 것은 예외가 발생할 가능성이 있는 API 메소드를 사용하는 개발자의 실수를 방지하기 위한 배려라고 볼 수도 있겠지만, 실제로는 예외를 제대로 다루고 싶지 않을 만큼 짜증나게 만드는 우너인이 되기도 한다.

자바가 처음 만들어질 때 많이 사용되던 애플릿이나 AWT, 스윙을 사용한 독립형 애플리케이션에서는 통제 불가능한 시스템 예외라고 할지라도 애플리케이션의 작업이 중단되지 않게 해주고 상황을 복구해야 했다. 예를 들어 워드의 팡리 열기 기능에서 사용자가 입력한 이름에 해당하는 파일을 찾을 수 없다고 애플리케이션이 종료돼버리게 할 수는 없다.

하지만 자바 엔터프라이즈 서버환경은 다르다. 수많은 사용자가 동시에 요청을 보내고 각 요청이 독립적인 작업으로 취급된다. 하나의 요청을 처리하는 중에 예외가 발생하면 해당 작업만 중단시키면 그만이다. 독립형 애플리케이션과 달리 서버의 특정 계층에서 에외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니케이션하면서 예외상황을 복구할 수 있는 방법이 없다.

차라리 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 게 좋다. 또는 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우라면 빨리 해당 요청 작업을 취소하고 서버 관리자나 개발자에게 통보해주는 편이낫다. 자바의 환경이 서버로 이동하면서 체크 예외의 활용도와 가치는 점점 떨어지고 있다. 자칫하면 throws Exception으로 점철된 아무런 의미도 없는 메소드들을 낳을 뿐이다. 그래서 대응이 불가능한 체크 예외라면 빨리 런타임 예외로 전환해서 던지는 게 낫다.

자바 초기부터 있었던 JDK의 API와 달리 최근에 등장하는 표준 스펙 또는 오픈소스 프레임워크에서는 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화되고 있다. 예전에는 복구할 가능성이 조금이라도 있다면 체크 예외로 만든다고 생각했는데, 지금은 항상 복구할 수 있는 예외가 아니라면 일단 언체크 예외로 만드는 경향이 있다. 언체크 에외라도 필요하다면 얼마든지 catch 블록으로 잡아서 복구하거나 처리할 수 있다. 하지만 대개는 복구 불가능한 상황이고 보나마나 RuntimeException 등으로 포장해서 던져야 할 테니 아예 API 차원에서 런타임 예외를 던지도록 만든느 것이다.

#### add() 메소드의 예외처리
이전에 나온 add() 메소드는 DuplicatedUserIdException과 SQLException 두 가지의 체크 예외를 던지게 되어 있다. JDBC 코드에서 SQLException이 발생할 수 있는데, 그 원인이 ID 중복이라면 좀 더 의미 이쓴ㄴ 예외인 DuplicatedUserIdException으로 전환해주고, 아니라면 SLQException을 그대로 던지게 했다. DuplicatedUserIdException은 충분히 복구 가능한 예외이므로 add() 메소드를 사용하는 쪽에서 잡아서 대응할 수 있다. 하지만 SQLException은 대부분 복구 불가능한 예외이므로 잡아봤자 처리할 것도 없고, 결국 throws를 타고 계속 앞으로 전달되다가 애플리케이션 밖으로 던져질 것이다. 그럴 바에는 그냥 런타임 예외로 포장해 던져버려서 그 밖의 메소드들이 신경 쓰지 않게 해주는 편이 낫다.

DuplicatedUserIdException도 굳이 체크 예외로 둬야 하는 것은 아니다. DuplicatedUserIdException처럼 의미 있는 예외는 add() 메소드를 바로 호출한 오브젝트 대신 더 앞단의 오브젝트에서 다룰 수 도 있다. 어디에서든 DuplicatedUserIdException을 잡아서 처리할 수 있다면 굳이 체크 예외로 만들지 않고 런타임 예외로 만드는게 낫다. 대신 add() 메소드는 명시적으로 DuplicatedUserIdException을 던진다고 선언해야 한다. 그래야 add() 메소드를 사용하는 코드를 만드는 개발자에게 의미 있는 정보를 전달해줄 수 있다. 러타임 예외도 throws로 선언할 수 있으니 문제 될 것은 없다.

이 방법을 이용해 add() 메소드를 수정해보자. 먼저 사용자 아이닥 중복됐을 때 사용하는 DuplicateUserIdException을 만든다. 필요하다면 언제든 잡아서 처리할 수 있도록 별도의 예외로 정의하기는 하지만, 필요 없다면 신경 쓰지 않아도 되도록 RuntimeException을 상속한 런타임 예외로 만든다. 중첩 예외를 만들 수 있도록 생성자를 추가해주는 것을 잊지 말다. 메세지나 예외상황을 전달하는 데 필요한 정보를 더 넣을 수도있다. 아래는 이렇게 만들어진 예외클래스다.

~~~java
// 아이디 중복시 사용하는 예외
public class DuplicateUserIdException extends RuntimeException {
  public DuplicateUserIdException(Throwable cause) {
    super(cause);
  }
}
~~~
이제 add() 메소드를 수정하자. 기존에는 SQLException을 직접 메소드 밖으로 던지게 했는데, 이제는 런타임 예외로 전환해서 던지도록 만든다. 기존의 아이디 중복 때문에 SQLException이 발생한 경우에는 DuplicateUserIdException을 던지게 하는 코드는 그대로 두면 된다.

이제 특별한 의미를 가지는 DuplicateUserIdException 외에 시스템 예외에 해당하는 SQLException은 언체크 예외가 됐다. 따라서 메소드 선언의 throws에 포함시킬 필요가 없다. 반면에 역시 언체크 예외로 만들어지긴 했지만 add() 메소드를 사용하는 쪽에서 아이디 중복 예외를 처리하고 싶은 경우 활용할 수 있음을 알려주도록 DuplicateUserIdException을 메소드의 throws 선언에 포함시킨다.

~~~java
// 예외처리 전략을 적용한 add()
public void add() throws DuplicateUserIdException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능이 있는 다른 SQLException을 던지는 메소드를 호출하는 코드
  }
  catch(SQLException e) {
    if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw new DuplicateUserIdException(e); //예외 전환
    else
      throw new RuntimeException(e); //예외 포장
  }
}
~~~

이제 이 add() 메소드를 사용하는 오브젝트는 SQLException을 처리하기 위해 불필요한 throws 선언을 할 필요는 없으면서, 필요한 경우 아이디 중복 상황을 처리하기 위해 DuplicateUserIdException을 이용할 수 있다. DuplicateUserIdException이 발생한 경우라면 사용자가 요청한 아이디 대신 사용할 수 있는 추천 아이디를 만들어 아이디 중복 체크 메세지와 함께 제공해주는 방법을 사용하면 좋을 듯하다.

이렇게 런타임 예외를 일반화해서 사용하는 방법은 여러모로 장점이 많다. 단, 런타임 예외로 만들었기 때문에 사용에 더 주의를 기울일 필요도 있다. 컴파일러가 예외처리를 강제하지 않으므로 신경 쓰지 않으면 예외상황을 충분히 고려하지 않은 수도 있기 때문이다. 런타임 예외를 사용하는 경우에는 API 문서나 레퍼런스 문서 등을 통해, 메소드를 사용할 때 발생할 수 있는 예외의 종류와 원인, 활용 방법을 자세히 설명해두자.

#### 애플리케이션 예외
런타임 예외 중심의 전략은 굳이 이름을 붙이자면 낙관적인 예외처리 기법이라고 할 수 있다. 일단 복구할 수 있는 예외는 없다고 가정하고 예외가 생겨도 어차피 런타임 예외이므로 시스템 레벨에서 알아서 처리해줄 것이고, 꼭 필요한 경우는 런타임 예외라도 잡아서 복구하거나 대응해줄 수 있으니 문제 될 것이 없다는 낙관적인 태도를 기반으로하고 있다. 이런 면에서 직접 처리할 수 없는 예외가 대부분이라고 하더라도 혹시 놓치는 예외가 있을 수 있으니, 일단 잡고 보도록 강제하는 체크 예외의 비관적인 접근 방법과 대비된다.
반면에 시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch 해서 무엇인가 조치를 취하도록 요구하는 예외도 있다. 이런 예외들을 일반적으로 애플리케이션 예외라고 한다.
예를 들어 사용자가 요청한 금액을 은행계좌에서 출금하는 기능을 가진 메소드가 있다고 생각해보자. 무턱대고 출금을 허용하고, 현재 잔고가 얼마인지 상관없이 요청한 금액만큼 계좌 잔액을 차감하도록 만드는 개발자는 없을 것이다. 당연히 현재 잔고를 확인하고, 허용하는 범위를 넘어서 출금을 요청하면 출금 작업을 중단시키고, 적절한 경고를 사용자에게 보내야 한다.

이런 기능을 담은 메소드를 설계하는 방법은 두 가지 있다.
첫 번째 방법은 정상적인 출금처리를 했을 경우와 잔고 부족이 발생했을 경우에 각각 다른 종류의 리턴 값을 돌려주는 것이다. 리턴 값을 일종의 결과 상대를 나타내는 정보로 활용한다. 예를 들어 정상적인 출금이 처리된 경우에는 요청금액 자체를 리턴하고, 잔고가 부족한 경우라면 0 또는 -1 같은 특별한 값을 리턴한다. 이 메소드를 호출한 쪽은 반드시 리턴 값을 확인한다. 경우에 따라 작업 흐름이 달라져야 하기 때문이다. 물론 이것은 시스템 오류가 아니므로 기술적으로 보면 두 가지 경우 모두 정상 흐름이다. 하지만 이렇게 리턴 값으로 결과를 확인하고, 예외상황을 체크하면 불편한 점도 있다.

우선 예외상황에 대한 리턴 값을 명확하게 코드화하고 잘 관리하지 않으면 혼란이 생길 수 있다. 정상적인 처리가 안 됐을 때 전달하는 값의 표준 같은 것은 없다. 어떤 개발자는 0을 생각할 수도 있고, -1이나 -999를 돌려주는 개발자도 있다. 일관된 예외상황에서의 결과 값에 대한 정책이 완벽하게 갖춰저 있고, 사전에 상수로 정의해둔 표준 코드를 사용하지 않는다면 자칫 개발자 사이의 의사소통 문제로 인해 제대로 동작하지 않을 위험이 있다. 또 한 가지 문제는 결과 값을 확인하는 조건문이 자주 등장한다는 점이다. 이런 식으로 결과를 돌려주는 메소드를 연이어 사용하는 경우라면 if 블록이 범벅된 코드가 이어질지 모른다. 코드는 지저분해지고 흐름을 파악하고 이해하기가 힘들어질 것이다.

두 번째 방법은 정상적인 흐름을 따르는 코드는 그대로 두고, 잔고 부족과 같은 예외 상황에서는 비즈니스적인 의미를 띤 예외를 던지도록 만드는 것이다. 잔고 부족인 경우라면 InsufficientBalanceException 등을 던진다. 예외상황을 처리하는 catch 블록을 메소드 호출 직후에 둘 필요는 없다. 정상적인 흐름을 따르지만 예외가 발생할 수 있는 코드를 try 블록 안에 깔끔하게 정리해두고 예외상황에 대한 처리는 catch 블록에 모아 둘 수 있기 때문에 코드를 이해하기도 편하다. 번거로운 if 문을 남발하지 않아도 된다.

이때 사용하는 예외는 의도적으로 체크 예외로 만든다. 그래서 개발자가 잊지 않고 잔고 부족처럼 자주 발생 가능한 예외상황에 대한 로직을 구현하도록 강제해주는 게 좋다. 무책임하게 throws Exception을 습관적으로 달아놓은 경우라면 이마저도 놓칠 가능성이 있긴 하지만, 기본적으로 런타임 예외로 만들어두는 것보다는 상대적으로 안전하다.

아래는 예금을 인출해서 처리하는 코드를 정상 흐름으로 만들어두고, 잔고 부족을 애플리케이션 예외로 만들어 처리하도록 만든 코드다. 애플리케이션 예외인 InsufficientBalanceException을 만들 때는 예외상황에 대한 상세한 정보를 담고 있도록 설계할 필요가 있다. 잔고가 부족한 경우라면 현재 인출 가능한 최대 금액은 얼마인지를 확인해서 예외 정보에 넣어준다면 좋을 것이다.

~~~java
// 애플리케이션 예외를 사용한 코드
try {
  BigDecimal balance = account.withdraw(amount);
  ...
  // 정상적인 처리 결과를 출력하도록 진행
}
catch(InsufficeientBalanceException e) {
  // InsufficientBalanceException에 담긴 인출 가능한 잔고금액 정보를 가져옴
  BigDecimal availFunds = e.getAvailFunds();
  ...
  // 잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행
}
~~~

### SQLException은 어떻게 됐나?
지금까지 다룬 예외처리에 대한 내용은 JdbcTemplate을 적용하는 중에 throws SQLException 선언이 왜 사라졌는가를 설명하는 데 필요한 것이었다. 스프링의 예외처리 전략과 원칙을 알고 있어야 하기 때문이다. 지금까지 살펴본 예외처리에 관한 내용을 바탕으로, DAO에 존재하는 SQLException에 대해 생각해보자.

먼저 생각해볼 사항은 SQLException은 과연 복구가 가능한 예외인가이다. 99%의 SQLException은 코드 레벨에서는 복구할 방법이 없다. 프로그램의 오류 또는 개발자의 부주의 때문에 발생하는 경우이거나, 통제할 수 없는 외부상황 때문에 발생하는 것이다. 예를 들어 SQL 문법이 틀렸거나, 제약조건을 위반했거나, DB 서버가 다운됐다거나, 네트워크가 불안정하거나, DB 커넥션 풀이 꽉 차서 DB 커넥션을 가져올 수 없는 경우 등이다.

시스템의 예외라면 당연히 애플리케이션 레벨에서 복구할 방법이 없다. 관리자나 개발자에게 빨리 예외가 발생했다는 사실이 알려지도록 전달하는 방법밖에는 없다. 마찬가지로 애플리케이션 코드의 버그나 미처 다루지 않았던 범위를 벗어난 값 때문에 발생한 예외도 역시 복구할 방법이 없다. INSERT 문에 넣을 파라미터 값을 미리 체크하지 않아서 발생하는 SQLException을 어떻게 복구할 것인가? 입력 단계에서 검증을 강화해야 한다는 사실을 개발자가 빨리 인식할 수 있도록 발생한 예외를 빨리전달하는 것 외에는 할 수 있는게 없다.

앞에서 잠깐 살펴본 ID 중복 문제를 시행착오 기법으로 확인하는 조금 무식한 접근방법 정도라면 모를까, 대부분의 SQLException은 복구가 불가능하다. 더군다나 DAO 밖에서 SQLException을 다룰 수 있는 가능성은 거의 없다. 따라서 예외처리 전략을 적용해야 한다. 필요도 없는 기계적인 throws 선언이 등장하도록 방치하지 않고 가능한한 빨리 언체크/런타임 예외로 전환해줘야 한다.

스프링의 JdbcTemplate은 바로 이 예외처리 전략을 따르고 있다. JdbcTemplate 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다. 따라서 JdbcTemplate을 사용하는 UserDao 메소드에선 꼭 필요한 경우에만 런타임 예외인 DataAccessException을 잡아서 처리하면 되고 그 외의 경우에는 무시해도 된다. 그래서 DAO 메소드에서 SQLException이 모두 사라진 것이다.

JdbcTemplate의 update(), queryForInt(), query() 메소드 선언을 잘 살펴보면 다음과 같인 모두 throws DataAccessException이라고 되어 있음을 발견할 수 있다. throws로 선언되어 있긴 하지만 DataAccessException이 런타임 예외이므로 update()를 사용하는 메소드에서 이를 잡거나 다시 던질 의무는 없다.
~~~java
public intupdate(final String sql) throws DataAccessException { ... }
~~~

그 밖에도 스프링의 API 메소드에 정의되어 있는 대부분의 예외는 런타임 예외다. 따라서 발생 가능한 예외가 있다고 하더라도 이를 처리하도록 강제하지 않는다.

## 예외 전환
예외를 다른 것으로 바꿔서 던지는 예외 전환의 목적은 두 가지라고 설명했다. 하나는 앞에서 적용해본 것처럼 런타임 예외로 포장해서 굳이 필요하지 않은 catch/throws를 줄여주는 것이고, 다른 하나는 로우레벨의 예외를 좀 더 의미 있고 추상화된 예외로 바꿔서 던져주는 것이다.

스프링의 JdbcTemplate이 던지는 DataAccessException은 일단 런타임 예외로 SQLException을 포장해주는 역할을 한다. 그래서 대부분 복구가 불가능한 예외인 SQLException에 대해 애플리케이션 레벨에서는 신경쓰지 않도록 해주는 것이다. 또한 DataAccessException은 SQLException에 담긴 다루기 힘든 상세한 예외정보를 의미 있고 일관성 있는 예외로 전환해서 추상해주려는 용도로 쓰이기도 한다.

### JDBC의 한계
JDBC는 자바 표준 JDK에서도 가장 많이 사용되는 기능 중의 하나다. DB를 이용해 데이터를 저장하고, 필요한 정보를 조회하는 기능은 대부분의 프로그램에서 필요하기 때문이다. 만약 DB별로 다른 API를 제공하고 이를 사용해야 한다고 상상해보자. DB가 바뀔 때마다 DAO 코드도 모두 바뀔 것이고, 제각각 다른 API 사용법을 익여햐 할 테니 상상만 해고 끔찍하다.

JDBC는 자바를 이용해 DB에 접근하는 방법을 추상화된 API 형태로 정의해놓고, 각 DB 업체가 JDBC 표준을 따라 만들어진 드라이버를 제공하게 해준다. 내부 구현은 DB마다 다르겠지만 JDBC의 Connection, Statement, ResultSet 등의 표준 인터페이스를 통해 그 기능을 제공해주기 때문에 자바 개발자들은 표준화된 JDBC의 AIP에만 익숙해지면 DB의 종류에 상관없이 일관된 방법으로 프로그램을 개발할 수 있다. 인터페이스를 사용하는 객체지향 프로그래밍 방법의 장점을 잘 경험할 수 있는 것이 바로 이 JDBC다.

하지만 DB 종류에 상관없이 사용할 수 있는 데이터 액세스 코드를 작성하는 일은 쉽지 않다. 표준화된 JDBC API가 DB 프로그램 개발 방법을 학습하는 부담은 확실히 줄여주지만 DB를 자유롭게 변경해서 사용할 수 있는 유연한 코드를 보장해주지는 못한다. 현실적으로 DB를 자유롭게 바꾸어 사용할 수 있는 DB 프로그램을 작성하는 데는 두 가지 걸림돌이 있다.

#### 비표준 SQL
첫째 문제는 JDBC 코드에서 사용하는 SQL이다. SQL은 어느 정도 표준화된 언어이고 몇 가지 표준 규약이 있긴 하지만, 대부분의 DB는 표준을 따르지 않는 비표준 문법과 기능도 제공한다. 이런 미표준 특정 DB 전용 문법은 매우 폭넓게 사용되고 있다. 해당 DB의 특별한 기능을 사용하거나 최적화된 SQL을 만들 때 유용하기 때문이다.

대용량 데이터를 처리하는 경우 성능을 향상시키기 위해 최적화 기법을 SQL에 적용하거나, 웹 화면의 페이지 처리를 위해 가져오는 로우의 시작 위치와 개수를 지정하거나, 쿼리에 조건을 포함시킨다거나, 특별한 기능을 제공하는 함수를 SQL에 사용하려면 대부분 비표준 SQL 문장이 만들어진다. 이렇게 작성된 비표준 SQL은 결국 DAO 코드에 들어가고, 해당 DAO는 특정 DB에 대해 종속적인 코드가 되고 만ㄷ다. 다른 DB로 변경하려면 DAO에 담긴 SQL을 적지 않게 수정해야 한다. 보통은 DB가 자주 변경되지도 않고, 사용하는 DB에 최적화하는 것이 중요하므로 비표준 SQL을 거리낌없이 사용한다. 하지만 DB의 변경 가능성을 고려해서 유연하게 만들어야 한다면 SQL은 제법 큰 걸림돌이 된다.

이 문제의 해결책을 생각해보면, 호환 가능한 표준 SQL만 사용하는 방법과, DB별로 별도의 DAO를 만들거나 SQL을 외부에 독립시켜 DB에 따라 변경해 사용하는 방법이 있다. 표준 SQL만을 사용할 경우, 당장에 웹 프로그램에서 자주 필요로 하는 페이징 쿼리에서부터 문제가 된다. 따라서 표준 SQL만 사용하는 방법은 간단한 예제 프로그램이라면 모를까 그다지 현실성이 없다. 결국 사용할 수 있는 방법은 DAO를 DB별로 만들어 사용하거나 SQL을 외부에서 독립시켜서 바꿔 쓸 수 있게 하는 것이다. 스프링의 DI를 적용하기 좋은 이런 방법들은 7장에서 다시 볼것이다.

#### 호환성 없는 SQLException의 DB 에러정보
두 번째 문제는 바로 SQLException이다. DB를 사용하다가 발생할 수 있는 예외의 원인은 다양하다. SQL의 문법 오류도 있고, DB 커넥션을 가져오지 못했을 수도 있으며, 테이블이나 필드가 존재하지 않거나, 키가 중복되거나 다양한 제약조건을 위배하는 시도를 한 경우, 데드락에 걸렸거나 락을 얻지 못했을 경우 등 수백여 가지에 이른다.

문제는 DB마다 SQL만 다른 것이 아니라 에러의 종류와 원인도 제각각이라는 점이다. 그래서 JDBC는 데이터 처리 중에 발생하는 다양한 예외를 그냥 SQLException 하나에 모두 담아버린다. JDBC API는 이 SQLException 한 가지만 던지도록 설계되어 있다. 예외가 발생한 원인은 SQLException 안에 담긴 에러 코드와 SQL 상태정보를 참조해봐야 한다. 그런데 SQLException의 getErrorCode()로 가져올 수 있는 DB 에러 코드는 DB별로 모두 다르다. DB 벤더가 정의한 고유한 에러 코드를 사용하기 떄문이다.

앞에서 만든 add() 메소드에선 새로운 사용자를 등록하다가 키가 중복돼서 예외가 발생하는 경우를 확인하기 위해 다음과 같은 방법을 사용했다.
~~~java
if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY) { ... }
~~~

SQLException의 에러 코드를 이용해 중복된 값의 등록이 원인인지 확인하는 것이다. 그런데 여기서 사용한 에러 코드는 MySQL 전용 코드일 뿐이다. DB가 MySQL에서 오라클이나 SQLServer로 바뀐다면 에러 코드도 달라지므로 이 코드는 기대한 대로 동작하지 못할 것이다.

그래서  SQLException은 예외가 발생했을 때의 DB 상태를 담은 SQL 상태정보를 부가적으로 제공한다. getSQLState() 메소드로 예외상황에 대한 상태정보를 가져올 수 있다. 이 상태정보는 DB별로 달라지는 에러 코드를 대신할 수 있도록, Open Group의 XOPEN SQL 스팩에 정의된 SQL 상태 코드를 따르도록 되어 있다. XOPEN SQL 상태 코드 외에도 JDBC 3.0에서는 SQL 99의 관례를, JDBC 4.0에서는 SQL2003의 관례를 따르도록 정의되어 있기는 하다.

예를 들면 통신장애로 DB 연결에 실패했을 경우에는 08S01, 테이블이 존재하지 않는 경우에는 42S02와 같은 식으로 DB 독립적인 표준 상태 코드가 정의되어 있다. 앞의 두 자리는 클래스 코드, 뒤의 세 자리는 서브클래스 코드로 분류되어 있기도 하다.
SQLException의 이러한 상태 코드를 제공하는 이유는 DB에 독립적인 에러정보를 얻기 위해서다. 그런데 문제는 DB의 JDBC 드라이버에서 SQLException을 담을 상태코드를 정확하게 만들어주지 않는다는 점이다. 어떤 경우에는 아예 표준 코드와는 상관없는 엉뚱한 값이 들어 있기도 하고, 어떤 DB는 클래스 코드까지는 바로 오지만, 서브클래스 코드는 일체 무시하고 값을 다 0으로 넣는다거나 하는 식이다. 결과적으로 이 SQL 상태 코드를 믿고 결과를 파악하도록 코드를 작성하는 것은 위험하다.
결국 호환성 없는 에러 코드와 표준을 잘 따르지 않는 상태 코드를 가진 SQLException만ㄴ으로 DB에 독립적인 유연한 코드를 작성하는 건 불가능에 가깝다.

### DB 에러 코드 매핑을 통한 전환
DB 종류가 바뀌더라도 DAO를 수정하지 않으려면 이 두 가지 문제를 해결해야 한다. SQL과 관련된 부분은 뒤에서 다루기로 하고, 여기서는 SQLException의 비표준 에러 코드와 SQL 상태정보에 대한 해결책을 알아보자.

SQLException에 담긴 SQL 상태 코드는 신뢰할 만한 게 아니므로 더 이상 고려하지 않겠다. 차라리 DB 업체별로 만들어 유지해오고 있는 DB 전용 에러 코드가 더 정확한 정보라고 볼 수 있다. SQL 상태 코드는 JDBC 드라이버를 만들 때 들어가는 것이므로 같은 DB라고 하더라도 드라이버를 만들 때마다 달라지기도 하지만, DB 에러 코드는 DB에서 직접 제공해주는 것이니 버전이 올라가더라도 어느 정도 일관성이 유지된다.

해결 방법은 DB별 에러 코드를 참고해서 발생한 예외의 원인이 무엇인지 해석해주는 기능을 만드는 것이다. 키 값이 중복돼서 중복 오류가 발생하는 경우에 MySQL 이라면 1062, 오라클이라면 1, DB2라면 -803이라는 에러 코드를 받게 된다. 이런 에러 코드 값을 확인할 수 있다면, 키 중복 때문에 발생하는 SQLException을 DuplicateKeyException이라는 의미가 분명히 드러나는 예외로 전환할 수 있다. DB 종류에 상관없이 동일한 상황에서 일관된 예외를 전달받을 수 있다면 효과적인 대응이 가능하다.

스프링은 DataAccessException이라는 SQLException을 대체할 수 있는 런타임 예외를 정의하고 있을 뿐 아니라 DataAccessException의 서브클래스로 세분화된 예외 클래스들을 정의하고 있다. SQL 문법 때문에 발생하는 에러라면 BadSqlGrammarException을 DB 커넥션을 가져오지 못했을 때는 DataAccessResourceFailureException을, 데이터의 제약조건을 위배했거나 일관성을 지키지 않는 작업을 수행했을 때는 DataIntegrityViolationException을, 그중에서도 중복 키 때문에 발생한 경우는 DuplicatedKeyException을 사용할 수 있다. 이 외에도 데이터 액세스 작업 중에 발생할 수 있는 예외상황을 수십 가지 예외로 분류하고 이를 추상화해 정의한 다양한 예외 클래스를 제공한다.

문제는 DB마다 에러 코드가 제각각이라는 점이다. DAO 메소드나 JdbcTemplate등의 코드에서 일일이 DB별로 에러 코드의 종류를 확인하는 작업을 수행하는 건 부담이 너무 크다. 대신 스프링은 DB별 에러 코드를 분류해서 스프링이 정의한 예외 클래스와 매핑해놓은 에러 코드 매핑정보 테이블을 만들어두고 이를 이용한다. 예를 들면 오라클용으로 아래와 같은 내용의 에러 코드 정보가 매핑파일에 담겨 있다.
~~~xml
<bean id="Oracle" class="org.springframework.jdbc.support.SQLErrorCodes">
  <property name="badSqlGrammarCodes">
    <value>900,903,904,917,936,942,17006</value>
  </property>
  <property name="invalidResultSetAccessCodes">
    <value>17003</value>
  </property>
  <property name="duplicateKeyCodes">
    <value>1</value>
  </property>
  <property name="dataIntegrityViolationCodes">
    <value>1400,1722,2291,2292</value>
  </property>
  ...
~~~

JdbcTemplate은 SQLException을 단지 런타임 예외인 DataAccessException으로 포장하는 것이 아니라 DB의 에러 코드를 DataAccessException 계층 구조의 클래스 중 하나로 매핑해준다. 전환되는 JdbcTemplate에서 던지는 예외는 모두 DataAccessException의 서브클래스 타입이다. 드리아버나 DB 메타정보를 참고해서 DB 종류를 확인하고 DB별로 미리 준비된 위와 같은 매핑정보를 참고해서 적절한 예외 클래스를 선택하기 때문에 DB가 달라져도 같은 종류의 에러라면 동일한 예외를 받을 수 있는 것이다.

중복 캐 에러를 따로 분류해서 예외처리를 해줬던 이전의 add() 메소드를 스프링의 JdbcTemplate을 사용하도록 바꾸면 아래와 같이 간단해진다. JdbcTemplate은 체크 예외인 SQLException을 런타임 예외인 DataAccess Exception 계층구조의 예외로 포장해주기 때문에 add() 메소드에는 예외 포장을 위한 코드가 따로 필요 없다. 또, DB의 종류와 상관없이 중복 키로 인해 발생하는 에러는 DataAccessexception의 서브클래스인 DuplicateKeyException으로 매핑돼서 던져진다. add() 메소드를 사용하는 쪽에서 중복 키 상황에 대한 대응이 필요한 경우에 참고할 수 있도록 DuplicateKeyException을 메소드 선언에 넣어주면 편리하다.
DuplicateKeyException은 이전의 add()메소드의 경우와 달리 DB를 변경하더라도 동일한 예외가 던져지는 것이 보장된다. JdbcTemplate 안에서 DB별로 미리 준비된 에러 코드와 비교해서 적절한 예외를 던져주기 때문이다.

~~~java
// JdbcTemplate이 제공하는 에외 전환 기능을 이용하는 add() 메소드
public void add() throws DuplicateKeyException {
  // JdbcTemplate을 이용해 User를 add 하는 코드  
}
~~~
JdbcTemplate을 이용한다면 JDBC에서 발생하는 DB 관련 예외는 거의 신경 쓰지 않아도 된다.
그런데 중복키 에러가 발생했을 때 애플리케이션에서 직접 정의한 예외를 발생시키고 싶을 수 있다. 개발 정책 때문일 수도 있고, 스프링 DuplicateKeyException의 런타임 예외이기 때문에 예외처리를 강제하지 않는 것이 불안해서 그럴 수도 있다. 아무튼 애플리케이션 레벨의 체크 예외인 DuplicateUserIdException을 던지게 하고 싶다면 아래와 같이 스프링의 DuplicateKey Exception 예외를 전환해주는 코드를 DAO 안에 넣으면 된다.
~~~java
// 중복 키 예외 전환
public void add() throws DuplicateUserIdException {
  try {
    // JdbcTemplate을 이용해 User를 add 하는 코드
  }
  catch(DuplicateKeyException e) {
    // 로그를 남기는 등의 필요한 작업
    throw new DuplicateUserIdException(e); // 예외를 전환할 때는 원인이 되는 예외를 중첩하는 것이 좋다.
  }
}
~~~
JDK 1.6에 포함된 JDBC 4.0부터는 기존에 JDBC의 단일 예외 클래스였던 SQLException을 스프링의 DataAccessException과 비슷한 방식으로 좀 더 세분화해서 정의하고 있다. SQL 문법 오류인 경우는 SQLSyntaxErrorException, 제약조건 위반인 경우는 SQLIntegrityConstraintViolationException과 같은 식으로 세분화된 예외를 사용하도록 만들었다. 이 규약을 따르는 드라이버의 경우 좀 더 상세한 예외를 만들어서 전달할 수 있게 됐다.

하지만 SQLException의 서브클래스이므로 여전히 체크 예외라는 점과 그 예외를 세분화하는 기준이 SQL 상태정보를 이용한다는 점에서 여전히 문제점이 있다. 시간이 더 많이 지나고 JDK 6.0이상을 사용하며, JDBC 4.0의 스펙을 충실히 따라 정확한 상태 정보를 가지고 일관성 있는 예외를 만들어주는 JDBC 드라이버가 충분히 보급된다면 모르겠지만, 아직은 스프링의 엣러 코드 매핑을 통한 DataAccessException 방식을 사용하는 것이 이상적이다.

### DAO 인터페이스와 DataAccessException 계층구조
DataAccessException은 JDBC의 SQLException을 전환하는 용도로만 만들어진 건 안디ㅏ. DJBC 외의 자바 데이터 액세스 기술에서 발생하는 예외에도 적용된다. 자바에는 JDBC 외에도 데이터 액세스를 위한 표준 기술이 존재한다. JDO나 JPA는 JDBC와 마찬가지로 자바의 표준 퍼시스턴스 기술이지만 JDBC와는 성격과 사용 방법이 크게 다르다. 또한 오라클의 TopLink 같은 상용 제품이나 오픈소스인 하이버네이트 같은 표준을 따르긴 하지만 독자적인 프로그래밍 모델을 지원하는 ORM 기술도 있다. JDBC를 기반으로 하고, 성격도 비슷하지만 사용 방법과 API, 발생하는 예외가 다른 iBatis도 있다.
DataAccessException은 의미가 같은 예외라면 데이터 액세스 기술의 종류와 상관없이 일관된 예외가 발생하도록 ㅁ나들어준다. 데이터 액세스 기술에 독립적인 추상화된 예외를 제공하는 것이다. 스프링이 왜 이렇게 DataAccessException 계층구조를 이용해 기술에 독립적인 예외를 정의하고 사용하게 하는지 생각해보자.

#### DAO 인터페이스와 구현의 분리
DAO를 굳이 따로 만들어서 사용하는 이유는 무엇일까? 가장 중요한 이유는 데이터 액세스 로직을 담은 코드를 성격이 다른 코드에서 분리해놓기 위해서다. 또한 분리된 DAO는 전략 패턴을 적용해 구현 방법을 변경해서 사용할 수 있게 만들기 위해서이기도 하다. DAO를 사용하는 쪽에서는 dAO가 내부에서 어떤 데이터 액세스 기술을 사용하는지 신경 쓰지 않아도 된다. User와 같은 자바빈으로 ㅁ나들어진, 특정 기술에 독립적인 단순한 오브젝트를 주고받으면서 데이터 액세스 기능을 사용하기만 하면 된다. 그런 면에서 DAO는 인터페이스를 사용해 구체적인 클래스 정보와 구현 방법을 감추고, DI를 통해 제공되도록 만드는 것이 바람직하다.

그런데 DAO의 사용 기술과 구현 코드는 전략 패턴과 DI를 통해서 DAO를 사용하는 클라이언트에게 감출 수 있지만, 메소드 선언에 나타나는 예외정보가 문제가 될 수 있다. UserDao의 인터페이스를 분리해서 기술에 독립적인 인터페이스로 만들려면 아래와 같이 정의해야 한다.
~~~java
// 기술에 독립적인 이상적인 DAO 인터페이스
public interface UserDao {
  public void add(User user);//이렇게 선언하는 것이 과연 가능할까?
  ...
}
~~~

하지만 위의 메소드 선언은 사용할 수 없다. DAO에서 사용하는 데이터 액세스 기술의 AIP가 예외를 던지기 때문이다. 만약 JDBC API를 사용하는 UserDao구현 클래스의 add() 메소드라면 SQLException을 던질 것이다. 인터페이스의 메소드 선언에는 없는 예외를 구현 클래스 메소드의 throw에 넣을 수는 없다. 따라서 인터페이스 메소드도 다음과 같이 선언돼야 한다.

~~~java
public void add(User user) throws SQLException;
~~~
이렇게 정의한 인터페이스는 JDBC가 아닌 데이터 액세스 기술로 DAO 구현을 전환하면 사용할 수 없다. 데이터 액세스 기술의 API는 자신만의 독자적인 예외를 던지기 때문에 다음과 같이 인터페이스 메소드를 바꿔주면 모르겠지만, SQLException을 던지도록 선언한 인터페이스 메소드는 사용할 수 없다.

~~~java
public void add(User user) throws PersistentException; //JPA
public void add(User user) throws HibernateException; //Hiberante
public void add(User user) throws JdoException; // JDO
...
~~~
결국 인터페이스로 메소드의 구현은 추상화했지만 구현 기술마다 던지는 예외가 다르기 때문에 메소드의 선언이 달라진다는 문제가 발생한다. DAO 인터페이스를 기술에 완전히 독립적으로 만들려면 예외가 일치하지 않는 문제도 해결해야 한다.
가장 단순한 해결 방법은 모든 예외를 다 받아주는 throws Exception으로 선언하는 것이다.

~~~java
public void add(User user) throws Exception;
~~~
간단하긴 하지만 무책임한 선언이다.
다행해고 JDBC보다는 늦게 등장한 JDO, Hibernate, JPA 등의 기술은 SQLException 같은 체크 예외 대신 런타임 예외를 사용한다. 따라서 throws에 선언해주지 않아도 된다. 남은 것은 SQLException을 던지는 JDBC API를 직접 사용하는 DAO뿐인데, 이 경우에는 DAO 메소드 내에서 런타임 예외로 포장해서 던져줄 수 있다. JDBC를 이용한 DAO에서 모든 SQLException을 런타임 예외로 포장해주기만 한다면 DAO의 메소드는 처음 의도했던 대로 다음과 같이 선언해도 된다.

~~~java
public void add(User user);
~~~
이제 DAO에서 사용하는 기술에 완전히 독립적인 인터페이스 선언이 가능해졌다. 하지만 이것만으로 충분할까?
대부분의 데이터 액세스 예외는 애플리케이션에서는 복구 불가능하거나 할 필요가 없는 것이다. 그렇다고 모든 예외를 다 무시해야 하는 건 아니다. 중복 캐 에러처럼 비즈니스 로직에서 의미 있게 처리할 수 있는 예외도 있다. 애플리케이션에서는 사용하지 않더라도 시스템 레벨에서 데이터 액세스 예외를 의미 있게 분류할 필요도 있다. 문제는 데이터 액세스 기술이 달라지면 같은 상황에서도 다른 종류의 예외가 던져진다는 점이다. 중복 키 에러가 발생했을 때 JDBC로 만든 DAO에서는 SQLException이, JPA에서는 PersistenceException이, 하이버네티으에서는 HibernateException이 던져진다. 따라서 DAO를 사용하는 클라이언트 입장에서는 DAO의 사용 기술에 따라서 예외 처리 방법이 달라져야 한다. 결국 클라이언트가 DAO의 기술에 의존적이 될 수밖에 없다.
단지 인터페이스로 추상화하고, 일부 기술에서 발생하는 체크 예외를 런타임 예외로 전환하는 것만으론 불충분하다.

#### 데이터 액세스 예외 추상화와 DataAccessException 계층구조
그래서 스프링은 자바의 다양한 데이터 액세스 기술을 사용할 때 발생하는 예외들을 추상화해서 DataAccessException 계층구조 안에 정리해놓았다.

앞에서 살펴본 것처럼 스프링의 JdbcTemplate은 SQLException의 에러 코드를 dB 별로 매핑해서 그에 해당하는 의미 있는 DataAccessException의 서브클래스 중 하나로 전환해서 던져준다. 그렇다고 DataAccessException 클래스들이 단지 JDBC의 SQLException을 전환하는 용도로만 쓰이는 건 아니다.

DataAccessException은 자바의 주요 데이터 액세스 기술에서 발생할 수 있는 대부분의 예외를 추상화하고 있다. 데이터 액세스 기술에 상관없이 공통적인 예외도 있지만 일부 기술에서만 발생하는 예외도 있다. JPA, 하이버네이트처럼 ORM에서는 발생하지만 JDBC에는 없는 예외가 있다. 스프링의 DataAccessException은 이런 일부 기술에서만 공통적으로 나타나는 예외를 포함해서 데이터 액세스 기술에서 발생 가능한 대부분의 예외를 계층구조로 분류해놓았다.

예를 들어 JDBC, JDO, JPA, 하이버네이트에 상관없이 데이터 액세스 기술을 부정확하게 사용했을 때는 InvalidDataAccessResourceUsageException 예외가 던져진다. 이를 다시 구체적으로 세분화하면 JDBC에서 발생할 수 있는 BadSqlGrammarException이나, 하이버네이트에서 발생하는 HibernateQueryException 또는 잘못된 타입을 사용하려고 했을 때 발생하는 TypeMismatchDataAccessException 등으로 구본된다. InvalidDataAccessResourceUsageException 예외는 거의 대부분 프로그램을 잘못 작성해서 발생하는 오류다. 스프링이 기술의 종류에 상관없이 이런 성격의 예외를 InvalidDataAccessResourceUsageException 타입의 예외로 던져주므로 시스템 레벨의 예외처리 작업을 통해 개발자에게 빠르게 통보해주도록 만들 수 있다.

또는 JDO, JPA, 하이버네이트처럼 오브젝트/엔티티 단위로 정보를 업데이트하는 경우에는 낙관적인 락킹(optimistic locking)이 발생할 수 있다. 이 낙관적인 락킹은 같은 정보를 두 명 이상의 사용자가 동시에 조회하고 순차적으로 업데이트 할 때, 뒤늦게 업데이트한 것이 먼저 업데이트한 것을 덮어쓰지 않도록 막아주는 데 쓸 수 있는 편리한 기능이다. 이런 예외들은 사용자에게 적절한 안내 메세지를 보여주고, 다시 시도할 수 있도록 해줘야 한다. 하지만 역시 JDO, JPA, 하이버네이트마다 다른 종류의 낙관적인 락킹 에외를 발생시킨다. 그런데 스프링의 예외 전환 방법을 적용하면 기술에 상관없이 DataAccessException의 서브 클래스인 ObjectOptimisticclockingFailureException으로 통일시킬 수 있다.
ORM 기술이 아니지마 JDBC 등을 이용해 직접 낙관적인 라킹 기능을 구현했다고 해보자. 이때는 아래처럼 ObjectOptimisticLockingFailureException의 슈퍼클래스인 OptimisticLockingFailureException을 상속해서 JdbcOptimisticLockFailureException을 정의해 사용할 수도 있다. 기술에 상관없이 낙관적인 락킹이 발생했을 때 일관된 방식으로 예외처리를 해주려면 OptimisticLockingFailureException을 잡도록 만들면 된다. 어떤 데이터 액세스 기술을 사용했는지에 상관없이 낙관적인 락킹을 처리하는 코드를 만들어낼 수 있다.

~~~
Jdbc를 이용한 낙관적인 락킹 예외 클래스의 적용
~~~
DataAccessException 계층구조에는 템플릿 메소드나 DAO 메소드에서 직접 활요할 수 있는 에외도 정의되어 있다. JdbcTemplate의 queryForObject() 메소드는 한 개의 로우만 돌려주는 쿼리에 사용하도록 되어 있다. 쿼리 실행 결과가 하나 이상의 로우를 가져오면, 템플릿 메소드의 사용 방법에 문제가 있거나 SQL을 잘못 작성한 것이다. 이런 경우에 JDBC에서는 예외가 발생하지 않는다. 하지만 JdbcTemplate에서 볼 때는 기대한 결과가 나오지 않은 예외상황이다. 이런 경우에 사용할 수 있도록 DataAccessException 계층구조에서는 IncorrectResultSizeDataAccessExeption이 정의도어 있다. queryForObject()에서는 좀 더 자세한 정보를 담은 서브클래스인 EmptyResultDataAccessException을 발생시킨다.
스프링의 데이터 액세스 전략이나 DataAccessException의 예외 사용법은 11장에서 자세히 살펴본다.

JdbcTemplate과 같이 스프링의 데이터 액세스 지원 기술을 이용해 DAO를 만들면 사용 기술에 독립적인 일관성 있는 예외를 던질 수 있다. 결국 인터페이스 사용, 런타임 예외 전환과 함게 DataAccessException 예외 추상화를 적용하면 데이터 액세스 기술과 구현 방법에 독립적인 이상적인 DAO를 만들 수가 있다.

### 기술에 독립적인 UserDao 만들기
#### 인터페이스 적용
지금까지 만들어서 써왔던 UserDao 클래스를 이제 인터페이스와 구현으로 분리해보자. 인터페이스와 구현 클래스의 이름을 정하는 방법은 여러 가지가 있다. 인터페이스를 구분하기 위해 인터페이스 이름 앞에는 I라는 접두어를 붙이는 방법도 있고, 인터페이스 이름은 가장 단순하게 하고 구현 클래스는 각가의 특징을 따르는 이름을 붙이는 경우도 있다. 여기서는 후자의 방법을 사용해보자. 사용자 처리 DAO의 이름은 userDao라 하고, JDBC를 이용해 구현한 클래스의 이름을 UserDaoJdbc라고 하자, 나중에 JPA나 하이버네이트로 구현한다면 그때는 UserDaoJpa, UserDaoHiberante라고 이름을 붙일 수 있다.

UserDao 인터페이스에는 기존 UserDao 클래스에서 DAO의 기능을 사용하려는 클라이언트들의 필요한 것만 추출해내면 된다. 아래는 인터페이스로 만든 UserDao다.

~~~java
// UserDao 인터페이스
public interface UserDao {
  void add(User user);
  User get(String id);
  List<User> getAll();
  void deleteAll();
  int getCount();
}
~~~
public 접근자를 가진 메소드이긴 하지만 UserDao의 setDataSource() 메소드는 인터페이스에 추가하면 안 된다는 사실에 주의하자. setDataSource() 메소드는 UserDao의 구현 방법에 따라 변경될 수 있는 메소드이고, UserDao를 사용하는 클라이언트가 알고 있을 필요도 없다. 따라서 setDataSource()는 포함시키지 않는다.
이제 기존의 UserDao 클래스는 다음과 같이 이름을 UserDaoJdbc로 변경하고 UserDao 인터페이스를 구현하도록 implements로 선언해줘야 한다.

~~~java
public class UserDaoJdbc implements UserDao { ... }
~~~
또 한 가지 변경할 사항은 스프링 설정파일의 userDao 빈 클래스 이름이다. userDao 빈 클래스를 아래와 같이 바꿔준다.

~~~xml
<!-- 빈 클래스 변경 -->
<bean id="userDao" class="springbook.dao.UserDaoJdbc">
  <property name="dataSource" ref="dataSource" />
</bean>
~~~
클래스 이름 외에는 변경할 게 없다. 보통 빈의 이름은 클래스 이름이 아니라, dataSource 빈이 그랬던 것처럼 클래스의 구현 인터페이스 이름을 따는 경우가 일반적이다. 그래야 나중에 구현 클래스를 바꿔도 혼란이 없기 때문이다.

#### 테스트 보완
이제 남은 것은 기존 UserDao 클래스의 테스트 코드다. 다음과 같은 userDao 인스턴스 변수 선언도 UserDaoJdbc로 변경해야 할까?
~~~java
public class UserDaoTest {
  @Autowired
  private UserDao dao; //UserDaoJdbc로 변경해야 하나?
}
~~~
굳이 그럴 필요는 없다. @Autowired는 스프링의 컨텍스트 내에서 정의된 빈 중에서 인스턴스 변수에 주입 가능한 타입의 빈을 찾아준다. UserDao는 UserDaoJdbc가 구현한 인터페이스이므로 UserDaoTest의 dao 변수에 UserDaoJdbc 클래스로 정의된 빈을 넣는데 아무런 무넺가 없다. UserDaoJdbc 오브젝트는 UserDao 타입이기 때문이다.

경우에 따라서 의도적으로 userDaoJdbc dao라고 선언할 수도 있다. 중요한 건 테스트의 관심이다. 그 구현 기술에 상관없이 DAo의 기능이 동작하는 데만 관심이 있다면, UserDao 인터페이스로 받아서 테스트 하는 편이 낫다. 나중에 다른 데이터 액세스 기술로 DAO 빈을 변경한다고 하더라도 이 테스트는 여전히 유효하다. 반면에 특정 기술을 사용한 UserDao의 구현 내용에 관심을 가지고 테으스하려면 테스트에서 @Autowired로 DI 받을 때 UserDaoJdbc나 UserDaoHibernate 같이 특정 타입을 사용해야 한다.

일단 UserDao 테스트는 DAO의 기능을 검증하는 것이 목적이지 JDBC를 이용한 구현에 관심이 있는 게 아니다. 그러니 UserDao라는 변수 타입을 그대로 두고 스프링 빈을 인터페이스로 가져오도록 만드는 편이 낫다.

아래는 UserDao의 인터페이스와 구현을 분리함으로써 데이터 액세스의 구체적인 기술과 UserDao의 클라이언트 사이에 DI가 적용된 모습을 보여준다. 아직 UserDao를 사용하는 애플리케이션 코드를 만들지는 않았지만 일단  테스트를 하나의 클라이언트라고 생각해도 좋다.

~~~
// UserDao 인터페이스와 구현의 분리
~~~
이제 UserDaoTest에 중복된 키를 가진 정보를 등록했을 때 어떤 에외가 발생하는지를 확인하기 위해 테스트를 하나 추가해보자. 이것은 UserDao의 로직을 테스트하기 위해서라기보다는 스프링이 데이터 액세스 에외를 다루는 기능을 직접 확인해보기 위한 것이니 일종의 학습 테스트다.

일반적으로 학습 테스트는 애플리케이션 코드에 대한 테스트와 분리해서 작성하는게 좋지만 여기서는 간단히 UserDaoTest에 넣어보겠다. 아래와 같은 메소드를 UserDaoTest에 추가해보자.

~~~java
// DataAccessException에 대한 테스트
@Test(expected=DataAccessException.class)
public void duplicateKey() {
  dao.deleteAll();

  dao.add(user1);
  dao.add(user1);//강제로 같은 사용자를 두 번 등록한다.
}
~~~
아이디가 같은 사용자를 두 번 add() 메소드로 등록하면 USER 테이블의 기본키 중복 때문에 에외가 발생할 것이다. 이때 스프링의 DataAccessException 예외 중의 하나가 던져져야 한다. 예외가 발생하면 성공이고 아니면 실패하게 만들어야 하므로 예외를 검증해주는 @Test(expected=..)를 이용한다. 메소드가 끝날 때까지 예외가 발생하지 않으면 테스트는 실패하게 된다.

테스트를 실행해보면 성공이다. 성공한 것으로 보아 DataAccessException 타입의 에외가 던져졌음이 분명한데, DataAccessException의 서브클래스일 수도 있으르모 구체적으로 어떤 에외인지 확인해볼 필요가 있다. 이런 경우에 어떤 예외가 발생했는지 확인해려면 테스트를 실패하게 만들면 된다.

이번엔 expected=DataAccessException.class 부분을 빼고 테스트를 실행해보자. 에외가 발생하면 테스트를 실패하지만, 에러 메세지를 통해 어떤 예외 클래스가 던져졌는지를 확인할 수 있다. expected 부분을 빼고 돌려보면 다음과 같은 예외가 발생했음을 알 수 있다.
~~~
org.springframework.dao.DuplicateKeyException: preparedStatementCallback; SQL ...
~~~

DuplicateKeyException은 DataAccessException의 서브 클래스로 DataIntegrityViolationException의 한 종류임을 알 수 있다. 이 테스트의 expected 항목을 DuplicateKeyException으로 바꾸고 실행해보자. 테스트는 역시 성공할 것이다. 좀 더 정확한 에외 발생을 확인하는 테스트가 됐다.

#### DataAccessException 활용 시 주의사항
이렇게 스프링을 활용하면 DB 종류나 데이터 액세스 기술에 상관없이 키 값이 중복이 되는 상황에서는 동일한 예외가 발생하리라고 기대할 것이다. 하지만 안타깝게도 DuplicateKeyException은 아직까지는 JDBC를 이용하는 경우에만 발생한다. 데이터 액세스 기술은 하이버네이트나 JPA를 사용했을 때도 동일한 예외가 발생할 것으로 기대하지만 실제로 다른 예외가 던져진다. 그 이유는 SQLException에 담긴 DB의 에러 코드를 바로 해석하는 JDBC의 경우와 달리 JPA나 하이버네이트, JDO 등에서는 각 기술이 재정의한 예외를 가져와 스프링이 최종적으로 DataAccessException으로 변환하는데, DB의 에러 코드와 달리 이런 예외들은 세분화되어 있지 않기 때문이다.

예를 들어 하이버네이트는 중복 키가 발생하는 경우에 하이버네이트의 ConstraintViolationException을 발생시킨다. 스프링은 이를 해석해서 좀 더 포괄적인 예외인 DataIntegrityViolationException으로 변환할 수 밖에 없다. 물론 DuplicateKeyException도 DataIntegrityViolationException의 한 종류다. 따라서 expected=DataIntegrityViolationException으로 해준다면 하이버네이트로 만든 DAO로 바꾼다고 하더라도 동일한 예외가 발생하기 때문에 DuplicateKeyException을 이용하는 경우에 비해서는 이용가치가 떨어진다.

DataAccessException이 기술에 상관없이 어느 정도 추상화된 공통 예외로 변환해주긴 하지만 근본적인 한계 때문에 완벽하다고 기대할 수는 없다. 따라서 사용에 주의를 기울여야 한다. DataAccessException을 잡아서 처리하는 코드를 만들려고 한다면 미리 학습 테스트를 만들어서 실제로 전환되는 예외의 종류를 확인해둘 필요가 있다.

만약 DAO에서 사용하는 기술의 종류와 상관없이 동일한 예외를 얻고 싶다면 DuplicateUserIdException처럼 직접 예외를 정의해두고, 각 DAO의 add() 메소드에서 좀 더 상세한 예외 전환을 해줄 필요가 있다. 하이버네이트 예외의 경우라도 중첩된 예외로 SQLException이 전달되기 때문에 이를 다시 스프링의 JDBGC 예외 전환 클래스의 도움을 받아서 처리할 수 있다.

학습 테스트를 하나 더 만들어서 SQLException을 직접 해석해 DataAccessException으로 변환하는 코드의 사용법을 살펴보자.
스프링은 SQLException을 DataAccessException으로 전환하는 다양한 방법을 제공한다. 가장 보편적이고 효과적인 방법은 DB 에러 코드를 이용하는 것이다. SQLException을 코드에서 직접 전환하고 싶다면 SQLExceptionTranslator를 사용하면 된다.
이 SQLErrorCodeSQLExceptionTranslator는 에러 코드 변환에 필요한 DB의 종류를 알아내기 위해 현재 연결된 DataSource를 필요로 한다. UserDaoTest에 아래처럼 DataSource 변수를 추가해서 DataSource 타입의 빈을 받아두도록 한다.

~~~java
// DataSource 빈을 주입받도록 만든 UserDaoTest
public class UserDaoTest {
  @Autowired UserDao dao;
  @Autowired DataSource dataSource;
}
~~~

아래는 이 DataSource를 사용해 SQLException에서 직접 DuplicateKeyException으로 전환하는 기능을 확인해보는 학습 테스트다.

~~~java
// SQLException 전환 기능의 학습 테스트
@Test
public void sqlExceptionTranslate() {
  dao.deleteAll();

  try {
    dao.add(user1);
    dao.add(user1);
  }
  catch(DuplicateKeyException ex) {
    SQLException sqlEx = (SQLException)ex.getRootCause();
    SQLExceptionTranslator set = //코드를 이용한 SQLException의 전환
      new SQLErrorCodeSQLExceptionTranslator(this.dataSource);

      assertThat(set.translate(null, null, sqlEx), is(DuplicateKeyException.class));
  }
}
~~~
먼저 JdbcTemplate을 사용하는 UserDao를 이용해 강제로 DuplicateKeyException을 발생시킨다. 이렇게 가져온 DuplicateKeyException은 중첩된 예외로 JDBC API에서 처음 발생한 SQLException을 내부에 갖고 있다. getRootCause() 메소드를 이용하면 중첩되어 있는 SQLException을 가져올 수 있다.

이제 검증해볼 사항은 스프링의 예외 전환 API를 직접 적용해서 DuplicateKeyException이 만들어지는가이다. 주입받은 dataSource를 이용해 SQLErrorCodeSQLExceptionTranslator의 오브젝트를 만든다. 그리고 SQLException을 파라미터로 넣어서 translate() 메소드를 호출해주면 SQLException을 DataAccessException 타입의 예외로 변환해준다. 변환된 DataAccessException 타입의 예외가 정확히 DuplicateKeyException 타입인지를 확인하면 된다. assertThat()의 is() 메소드에 클래스를 넣으면 오브젝트의 equals() 비교 대신 주어진 클래스의 인스턴스인지 검사해준다. 이 테스트가 성공한다면 코드에 의한 예외 전환이 잘 했음을 확인할 수 있다.

테스트는 물론 성공한다. DB에 상관없이 항상 DuplicateKeyException 예외로 전환 되는지 궁금하다면 DB를 바꿔서 해보는 것도 재밌을 것이다.

JDBC 외의 기술을 사용할 때도 DuplicateKeyException을 발생시키려면 SQLException을 가져와서 직접 예외 전환을 하는 방법을 생각해볼 수 도 있다. 또는 JDBC를 이용하지만 JdbcTemplate과 같이 자동으로 예외를 전환해주는 스프링의 기능을 사용할 수 없는 경우라도 SQLException을 그대로 두거나 의미 없는 RuntimeException으로 뭉뚱그려서 던지는 대신 스프링의 DataAccessException 계층의 예외로 전환하게 할 수 있다.

## 정리
4장에서는 엔터프라이즈 애플리케이션에서 사용할 수 있는 바람직한 예외처리 방법은 무엇인지를 살펴봤다. 또한 JDBC 예외의 단점이 무엇인지 살펴보고, 스프링이 제공하는 효과적인 데이터 액세스 기술의 예외처리 전략과 기능에 대해서도 알아봤다. 이 장에서 살펴본 주요 내용은 다음과 같다.

- 예외를 잡아서 아무런 조취를 취하지 않거나 의미 없는 throws 선언을 남발하는 것은 위험하다.
- 예외는 복구하거나 예외처리 오브젝트로 의도적으로 전달하거나 적절한 예외로 전환해야 한다.
- 좀 더 의미 있는 예외로 변경하거나, 불필요한 catch/throws를 피하기 위해 런타임 예외로 포장하는 두 가지 방법의 예외 전환이 있다.
- 복구할 수 없는 예외는 가능한 한 빨리 런타임 예외로 전환하는 것이 바람직하다.
- 애플리케이션의 로직을 담기 위한 예외는 체크 예외로 만든다.
- JDBC의 SQLException은 대부분 복구할 수 없는 예외이므로 런타임 예외로 포장해야 한다.
- SQLException의 에러 코드는 DB에 종속되기 때문에 DB에 독립적인 예외로 전환될 필요가 있다.
- 스프링은 DataAccessException을 통해 DB에 독립적으로 적용 가능한 추상화된 렁타임 예외 계층을 제공한다.
- DAO를 데이터 액세스 기술에서 독립시키려면 인터페이스 도입과 런타임 예외 전환, 기술에 독립적인 추상화된 예외로 전환이 필요하다.
