# 예외
자바 개발자가 가장 신경 쓰기 귀찮아하는 것 중의 하나가 바로 예외처리다. 그래서 예외와 관련된 코드는 자주 엉망이 되거나 무성의하게 만들어지기 쉽다. 때론 잘못된 예외처리 코드 때문에 찾기 힘든 버그를 낳을 수도 있고, 생각지 않았던 예외상황이 발생했을 때 상상 이상으로 난처해질 수도 있다.

이번장에서는 JdbcTemplate을 대표로 하는 스프링의 데이터 액세스 기능에 담겨 있는 예외처리와 관련된 접근 방법에 대해 알아보자.

## 사라진 SQLException
3장에서 JdbcContext로 만들었던 코드를 스프링의 JdbcTempalte을 적용하도록 바꾸면서 얼렁뚱땅 넘어간 부분이 있다. 바꾸기 전후의 deleteAll() 메소드를 비교해보자.

~~~java
// 전
public void deleteAll() throws SQLException {
  this.jdbcContext.executeSql("delete from users");
}

// 후
public void deleteAll() {
  this.jdbcTemplate.update("delete from users");
}
~~~
바꾸기 전에 있던 throws SQLException 선언이 바꾼 뒤로는 사라졌다. SQLException 은 JDBC API 의 메소드들이 던지는 것이므로 당연히 있어야한다. 비록 로그를 남기기 위해 catch를 했다고 해도 다시 JDBC 템플릿 메소드밖으로 던져서 예외상황이 발생했다는 사실을 알려야 한다. 그런데 JdbcTemplate을 적용한 코드에서는 사라졌다. SQLException은 어디로 간 것일까?

### 초난감 예외처리
JdbcTemplate이 어떤 짓을 했길래 SQLException이 사라졌는지 알아보기 위해 먼저 개발자들의 코드에서 종종 발견되는 초난감 예외처리의 대표코드를 살펴보자.

#### 에외 블랙홀
~~~ java
// 초난감 예외처리 코드
try {
  ...
} catch(SQLException e) { }
~~~
여기서 catch(SQLException e) {} 는 예외 발생을 무시해버리고 정상적인 상황인 것처럼 다음 라인으로 넘어가겠다는 의도가 있는 게 아니라면 연습 중에도 절대 만들어서는 안 되는 코드다.

JDBC API를 썼더니 IDE가 빨간 줄을 그어주며 '처리되지 않은 예외가 있다'고 에러를 표시해 준다. 이를 보고 자바 기초로 배운 try/catch 블록을 둘러싸주는 것으로 해결한다. 물론 컴파일 에러 메세지도 없어지고 별 문제 없이 동작한다.

이런 식의 코드가 자바 서적의 예제나 강의 자료에도 심심치 않게 등장하고, 유명 오픈소스 제품의 코드나 실전 프로젝트의 작성된 코드에서도 나타나는 것을 보면 초보자의 실수라고만 볼 수는 없다. 이런 잘못된 습관이 계속 남아 있는 게 문제의 원인일 것이다.

예외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 정말 위험하다. 왜냐하면 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다.

결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동작하거나, 메모리나 리소스가 소진되거나, 예상치 못한 다른 문제를 일으킬 것이다. 최종적으로는 오작동을 하거나 시스템 오류가 나서 개발자가 알아차렸을 때는 이미 조치를 취하기에 늦다. 더 큰 문제는 그 시스템 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 매우 힘들다는 점이다.

어떤 경우에도 위와 같이 빈 catch 블록을 사용하면 안된다.

아래의 코드도 마찬가지다
~~~java
} catch(SQLException e) {
  System.out.println(e);
}
~~~

~~~java
} catch(SQLException e) {
  e.printStackTrace();
}
~~~

예외가 발생하면 화면에 출력해주는데 어떤 점이 문제일까? 다른 로그나 메세지에 금방 묻혀버리면 놓치기 쉽상이며, 운영서버에 올라가면 콘솔로그를 누군가가 계속 모니터링하지 않는 한 심각한 폭탄으로 남아 있을 것이다. catch 블록을 이용해 화면에 메세지를 출력한 것은 예외 처리한 게 아니다.

예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 한 가지다. 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 개발자에게 분명하게 통보돼야 한다.

SQLException이 발생하는 이유는 SQL에 문법 에러가 있거나 DB에서 처리할 수 없을 정도로 데이터 액세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다. 그런데 그냥 예외를 무시하고 정상적으로 동작하고 있는 것처럼 모른 척 다음 코드로 실행을 이어간다는 건 말이 되지 않는다. 콘솔이나 로그에 예외 메시지를 출력하는 건 아무런 도움이 되지 않는다.

차라리 아래와 같은 코드가 더 낫다
~~~java
//그나마 나은 예외처리
} catch(SQLException e) {
  e.printStackTrace();
  System.exit(1);
}
~~~

물론 실전에서 이렇게 만들라는 것은 아니다. 예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라는 의미다. 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다. 메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해버려라.

#### 무의미하고 무책임한 throws
catch 블록으로 예외를 잡아봐야 해결할 방법도 없고 JDK API나 라이브러리가 던지는 각종 이름도 긴 예외들을 처리하는 코드를 매번 throws로 선언하기도 귀찮아지기 시작하면, 아래와 같이 메소드 선언에 throws EXception을 기계적으로 붙이는 개발자도 있다.

~~~java
// 초난감 예외처리4
public void methos1() throws EXception {
  method2();
  ...
}

public void method2() throws Exception {
  method3();
  ...
}

public void mehtod3() throws Exception {
  ...
}
~~~

API 등에서 발생하는 예외를 일일이 catch하기 귀찮고, 별 필요도 없으며 매번 정확하게 예외 이름을 적어서 선언하기도 귀찮으니 아예 throws Exception이라는, 모든 예외를 무조건 던저버리는 선언을 모든 메소드에 기계적으로 넣는 것이다. 예외를 흔적도 없이 먹어치우는 예외 블랙홀보다는 조금 낫긴 하지만 이런 무책임한 throws 선언도 심각한 문제점이 있다.

자신이 사용하려고 하는 메소드에 throws Exception이 선언되어 있다고 생각해보자, 그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다. 결국 이런 메소드를 사용하는 메소드에서도 역시 throws Exception을 따라서 붙이는 수밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다를 수 있는 기회를 박탈당한다.

예외를 무시해버리는 첫 번째 문제보다는 낫다고 하지만 이런 코드도 매우 안좋은 예외처리 방법이다.

이 두 가지 나쁜 습관은 어떤 경우에도 용납하지 않아야 한다.

### 예외의 종류와 특징
그렇다면 예외를 어떻게 다뤄야 할까? 예외처리에 관해서는 자바 개발자들 사이에서도 오랫동안 많은 논쟁이 있었다. 가장 큰 이슈는 체크 예외(checked exception)라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다.

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.

- Error
첫번째는 java.lang.Error 클래스의 서브클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다. OutOfMemoryError나 ThreadDeath 같은 에러는 CATCH 블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다.
따라서 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다.

- Exception과 체크 예외
java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.
Exception 클래스는 다시 체크 예외와 언체크 예외(unchecked exception)로 구분된다. 전자는 Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것들이고, 후자는 RunTimeException을 상속한 클래스들을 말한다.
RunTimeException은  Exception의 서브클래슫이므로 Exception의 일종이긴 하지만 자바는 이 RuntimeException과 그 서브클래스는 특별하게 다룬다. 아래는 Exception 클래스의 서브클래스를 체크 예외와 언체크 예외로 구분한 것이다.
~~~

~~~
일적으로 예외는 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다. 체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다. 사용할 메소드가 체크 예외를 던진다면 이를 catch 문으로 잡든지, 아니면 다시 throws를 정의해서 메소드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다.

- RuntimeException과 언체크/런타임 예외
java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 럼타임 예외라고도 한다. 에러와 마찬가지로 이 런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 된다. 물론 명시적으로 잡거나 선언해도 상관은 없다.
런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다. 대표적으로 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을 때 발생하는 NullPointerException이나, 허용되지 않는 값을 사용해서 메소드를 호출할 때 발생하는 IllegalArgumentException 등이 있다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다.

피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 마든 것이 런타임 예외다. 따라서 런타임 예외는 예상하지 못했던 예외상황에서 발생하는 게 아니기 때문에 굳이 catch나 throws를 사용하지 않아도 되도록 만든 것이다.

그런데 자바 언어를 설계하고 JDK를 개발한 사람들의 이런 설계의도는 현실과 잘 맞지 않았고 비난의 대상이 되기도 했다. 특히 체크 예외의 불필요성을 주장하는 사람들이 늘어갔다. 체크 예외가 예외처리를 강제하는 것 때문에 예외 블랙홀이나 무책임한 throws 같은 코드가 남발됐다. 최근에 새로 등장하는 자바 표준 스펙의 API들은 예상 가능한 예외상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있기도 하다.

### 예외처리 방법
일반적인 예외처리 방법을 살펴보고나서 효과적인 예외처리 전략을 생각해보자.

#### 예외 복구
첫 번째 처리 방법은 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다.

예를 들어 사용자가 요청한 파일을 읽으려고 시도했는데 어떤 문제로 읽히지 않아 IOException이 발생했다고 생각해보자. 이때는 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내해서 예외상황을 해결할 수 있다. 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해주는 것이다.

이런 경우 예외상황은 다시 정상으로 돌아오고 예외를 복구했다고 볼 수 있다. 단, IOException 에러 메세지가 사용자에게 그냥 던져지는 것은 예외 복구라고 볼 수 없다. 예외가 처리됐으면 비록 기능적으로는 사용자에게 예외상황으로 비쳐도 애플리케이션에서는 정상적으로 설계된 흐름을 따라 진행돼야 한다.

네트워크가 불안해서 가끔 서버에 접속이 잘 안 되는 열악한 환경에 있는 시스템이라면 원격 DB 서버에 접속하다 실패해서 SQLException이 발생하는 경우에 재시도를 해볼 수 있다. 네트워크 접속이 원할하지 않아서 예외가 발생했다면 일정 시간 대기했다가 다시 접속을 시도해보는 방법을 사용해서 예외상황으로부터 복구를 시도할 수 있다. 물론 정해진 횟수만큼 재시도해서 실패했다면 예외 복구는 포기해야 한다.

예외처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다. API를 사용하는 개발자로 하여금 예외상황이 발생할 수 있음을 인식하도록 도와주고 이에 대한 적절한 처리를 시도해보도록 요구하는 것이다.

아래는 통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY만큼 재시도를 하는 간단한 예이다. 사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구되게 할 수 있다.

~~~java
// 재시도를 통해 예외를 복구하는 코드
int maxretry = MAX_RETRY;
while(maxretry-- > 0) {
  try {
    ... // 예외가 발생할 가능성이 있는 시도
    return; // 작업 성공
  }
  catch(SomeException e) {
    // 로그 출력, 정해진 시간만큼 대기
  }
  finally {
    // 리소스 반납. 정리 작업
  }
}

throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
~~~

#### 예외처리 회피
두 번째 방법은 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다. throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 rethrow것이다.

예외를 자신이 처리하지 않고 회피하는 방법이다. 빈 catch 블록으로 잡아서 예외가 발생하지 않은 것처럼 만드는 경우는, 드물지만 특별한 의도를 가지고 예외를 복구했거나 아무 개념이 없어서 그런 것이지 회피한 것은 아니다. 예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리할 수 있도록 아래처럼 던져줘야 한다.

~~~java
// 예외처리 회피1
public void sadd() throws SQLException {
  ///JDBC API
}
~~~

~~~java
// 예외처리 회피2
public void add() throws SQLException {
  try {
    // JDBC API
  }
  catch(SQLException e) {
    // 로그 출력
    throw e;
  }
}
~~~
JdbcContext나 JdbcTemplate이 사용하는 콜백 오브젝트는 메소드 선언을 보면 알겠지만 ResultSet이나 PreparedStatement등을 이용해서 작업하다 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. 콜백 오브젝트의 메소드는 모두 thorws SQLException이 붙어 있다. SQLException을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문이다. 콜백 오브젝트의 메소드는 SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다.

하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다. 만약 DAO가 SQLException을 생각 없이 던져버리면 어떻게 될까? DAO를 사용하는 서비스 계층이나 웹 컨트롤러에서 과연 SQLException을 제대로 처리할 수 있ㅇ르까? 아마도 이런 경우라면 DAO에서 던진 SLQLException을 서비스 계층 메소드가 다시 던지고, 컨트롤러도 다시 던지도록 선언해서 예외는 그냥 서버로 전달되고 말 것이다. 아마도 throws SQLException과 같이 구체적인 예외를 던지도록 선언하기가 귀찮아서 모든 예외를 생각없이 던져버리게 하는 throws Exception을 사용할 가능성이 높다.

예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 qkdqjqdlfksms 분명한 확신이 있어야한다.

#### 예외 전환
마지막으로 예외를 처리하는 방법은 예외 전환(exception translation)을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것이다. 하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.

예외 전환은 보통 두 가지 목적으로 사용한다.
첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 핼줄 수 있는 예외로 바꿔주기 위해서다. API가 발생하는 기술적인 로우레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것이다.

예를 들어 새로운 사용자를 등록하려고 시도했을 때 아이디가 같은 사용자가 있어서 DB 에러가 발생하면 JDBC API는 SQLException을 발생시킨다. 이 경우 DAO 메소드가 SQLException을 그대로 밖으로 던져버리면, DAO를 이용해 사용자를 추가하려고 한 서비스 계층 등에서는 왜 SQLException이 발생헀는지 쉽게 알 방법이 없다. 로그인 아이디 중복 같은 경우는 충분히 예상 가능하고 복구 간으한 예외상황이다. 이럴 땐 DAO에서 SQLException의 정보를 해석해서 DuplicationUserIdException 같은 예외로 바꿔서 던져주는 게 좋다.
